# basics
brew 'mas'
brew 'bat'
brew 'watch'
brew 'wget'
brew 'jq'
brew 'tldr'
brew 'openssl'
brew 'rar'
brew 'tree'
cask 'iterm2'
brew 'zsh'
brew 'zsh-syntax-highlighting'
tap 'sambadevi/powerlevel9k'
brew 'powerlevel9k'
tap 'caskroom/fonts'
cask 'font-meslo-nerd-font'
brew 'bitwarden-cli'
cask 'dropbox'
brew 'nmap'

# development
brew 'terraform'
brew 'kubectl'
brew 'awscli'
cask 'docker'
cask 'google-cloud-sdk'
cask 'minikube'
cask 'jetbrains-toolbox'
cask 'postman'
cask 'insomnia'
cask 'adoptopenjdk8'
cask 'adoptopenjdk11'
brew 'nvm'
brew 'yarn'
cask 'sublime-text'
cask 'anaconda'
cask 'dotnet-sdk'
cask 'visual-studio-code'
cask 'visual-studio'
brew 'pidcat'
brew 'carthage'
brew 'v8' # for ruby


# usability
cask 'bettertouchtool'
cask 'scroll-reverser'

# finances
cask 'gnucash'

# media
cask 'google-chrome'
cask 'slack'
cask 'skype'
cask 'kindle'
cask 'spotify'
tap 'homebrew/cask-drivers'
cask 'sonos'
cask 'vlc'
